# Generated by Django 5.0.2 on 2024-05-13 05:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_admin', '0002_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, max_length=10, null=True)),
                ('product_name', models.CharField(blank=True, max_length=10, null=True)),
                ('product_sku', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('product_size', models.CharField(blank=True, max_length=10, null=True)),
                ('price', models.IntegerField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='images')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo_admin.category')),
                ('sub_category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo_admin.sub_category')),
            ],
        ),
    ]
